#!/bin/bash

if [ "$1" == "clean" ]; then
    echo "[nomadic] uninstalling..."
    shift
    cd ~/
    rm -fR ~/nomadic
    sudo rm -f /bin/nomadic
    rm -fR ~/cabage
    rm -fR ~/bin
    rm -fR ~/dwm
    rm -fR ~/radio
    rm -fR ~/media
    rm -fR ~/.arduino15
    rm -f .screenrc
    rm -f .irc.el
    redis-cli flushdb > /dev/null
    echo "[nomadic] uninstalled."
    echo "Continuing in 10 seconds.  Press Ctrl-c to stop..."
    sleep 10
fi

echo "[nomadic]"
if [ ! -d ~/nomadic ]; then
	cd ~
	git clone --quiet https://github.com/xorgnak/nomadic
else
	cd ~/nomadic && git pull
fi
sudo cp ~/nomadic/nomadic /bin/nomadic
echo "[nomadic] updated."

echo "[nomadic][cabage] "
if [ ! -d ~/cabage ]; then
    echo "[nomadic][cabage] get... "
    cd ~;
    git clone --quiet https://github.com/xorgnak/cabage && cd cabage && ./now;
    sudo cp work /bin/work
    echo "[nomadic][cabage] got! "
else
    cd ~/cabage && git pull
fi

echo ""
printf "[nomadic][gui] "
if [ ! -d ~/dwm ]; then
	printf "get... "
	cd ~;
	git clone --quiet https://github.com/xorgnak/dwm && cd dwm && ./now;
	printf "got! "
fi
printf "OK."

echo ""
printf "[nomadic][rtc] "
if [ ! `which peerjs` ]; then
	printf "get... "
	sudo apt-get install -y npm > /dev/null
	sudo npm install peer -g
	printf "got! "
fi
printf "OK."

echo ""
printf "[nomadic][iot] "
if [ ! -d  ~/.arduino15 ]; then
	printf "get... "
	cd ~;
	curl -fsSL https://raw.githubusercontent.com/arduino/arduino-cli/master/install.sh | sh -;
	cd bin;
	git clone https://github.com/xorgnak/node
	./arduino-cli config init;
	editor ~/.arduino15/arduino-cli.yaml
	./arduino-cli core update-index;
	printf "got! "
fi
printf "OK."

echo ""
printf "[nomadic][radio] "
if [ ! -d ~/radio ]; then
	printf "get... "
	sudo apt-get install -y rtl-sdr fldigi wsjtx gqrx-sdr lingot chirp multimon-ng;
	mkdir ~/radio
	printf "got! "
fi
printf "OK."

echo ""
printf "[nomadic][media] "
if [ ! -d ~/media ]; then
	printf "get... "
	cd ~;
	sudo apt-get install -y vlc audacity jaaa siggen butt darkice darksnow autoradio musescore mpd mpdtoys mpc ncmpc ncmpcpp mumble mumble-server gtranscribe espeak-ng-espeak
	mkdir ~/media
	printf "got! "
fi
printf "OK."

echo ""
echo "[nomadic] READY."
cd ~/cabage && ./now $*;
echo "[nomadic] GOODBYE."
exit 0
