#!/bin/bash

if [ ! -d ~/cabage ]; then
    cd ~;
    git clone https://github.com/xorgnak/cabage && cd cabage && ./now;
    sudo cp work /bin/work
fi

if [ "$1" == "add" ]; then
    if [ "$2" == "gui" ]; then
	cd ~;
	git clone https://github.com/xorgnak/dwm && cd dwm && ./now;
    elif [ "$2" == "arduino" ]; then
	cd ~;
	curl -fsSL https://raw.githubusercontent.com/arduino/arduino-cli/master/install.sh | sh -;
	cd bin;
	./arduino-cli config init;
	editor ~/.arduino15/arduino-cli.yaml
	./arduino-cli core update-index;
    elif [ "$2" == "radio" ]; then
	sudo apt install -y rtl-sdr;
    fi
else
	cd ../cabage && ./now $*;    
fi


