#!/bin/bash


function add_gui() {
    cd ~;
    git clone https://github.com/xorgnak/dwm && cd dwm && ./install.sh;
}
function add_sdr() {
    sudo apt install -y rtl-sdr;
}
function add_arduino() {
    cd ~;
    curl -fsSL https://raw.githubusercontent.com/arduino/arduino-cli/master/install.sh | sh -;
    cd bin;
    ./arduino-cli config init;
    ./arduino-cli core update-index;
}

function handle_input() {
    if [[ "$1" == "add" ]]; then
	if [[ "$2" == "gui" ]]; then
	    add_gui()
	elif [[ "$2" == "arduino" ]]; then
	    add_arduino();
	elif [[ "$2" == "radio" ]]; then
	    add_sdr();
	fi
    fi
}

echo "+-----[the NOMADIC feralizer]";
echo "|";
if [ -d ~/cabage ]; then
    handle_input($*);
else
  echo "+-> harvesting cabage.";
  cd ~;
  git clone https://github.com/xorgnak/cabage && cd cabage && ./now;
fi
echo "|";
echo "+-----[transformation complete]";
